parse:
  additional_commands:
    _jegp_add_target:
      pargs:
        nargs: 1
        flags:
        - EXCLUDE_FROM_ALL
      kwargs:
        TYPE: 1
        SOURCES: +
        COMPILE_OPTIONS: +
        LINK_LIBRARIES: +
        PROPERTIES: +
    _jegp_string:
      kwargs:
        SUBSTRING_AFTER: 1
        SUBSTRING: 1
        FOUND: 1
        JSON: 1
        FIND_ITH: 1
        VALUE: 1
        KEYS: 1+
