parse:
  additional_commands:
    _jegp_common_yaml_anchors:
      kwargs:
        PUBLIC_INTERFACE_PRIVATE: &public_interface_private
          kwargs:
            PUBLIC: +
            INTERFACE: +
            PRIVATE: +
    _jegp_add_target: &jegp_add_target
      pargs:
        nargs: 1
        flags:
        - EXCLUDE_FROM_ALL
      kwargs:
        TYPE: 1
        SOURCES: +
        COMPILE_OPTIONS: *public_interface_private
        LINK_LIBRARIES: *public_interface_private
        PROPERTIES: +
    _jegp_define_target: *jegp_add_target
    _jegp_string:
      kwargs:
        SUBSTRING_AFTER:
          pargs:
            nargs: 1
          kwargs:
            SUBSTRING: 1
            FOUND: 1
        JSON:
          pargs:
            nargs: 1
          kwargs:
            FIND_ITH: 1
            VALUE: 1
            KEYS: 1+
