parse:
  additional_commands:
    _jegp_add_target:
      pargs:
        nargs: 1
        flags:
        - EXCLUDE_FROM_ALL
      kwargs:
        TYPE: 1
        SOURCES: +
        COMPILE_OPTIONS: +
        LINK_LIBRARIES: +
        PROPERTIES: +
