function(_jegp_get_target_cpp_sources target out_list)
  get_target_property(sources "${target}" SOURCES)
  foreach(src IN LISTS sources)
    get_source_file_property(language "${src}" LANGUAGE)
    if(language STREQUAL "CXX")
      list(APPEND cpp_sources "${src}")
    endif()
  endforeach()
  set("${out_list}" "${cpp_sources}" PARENT_SCOPE)
endfunction()
