function(_jegp_get_target_cpp_sources target out_list)
  get_target_property(sources "${target}" SOURCES)
  foreach(src IN LISTS sources)
    cmake_path(GET src EXTENSION LAST_ONLY extension)
    string(REPLACE "." "" extension "${extension}")
    if(extension IN_LIST CMAKE_CXX_SOURCE_FILE_EXTENSIONS)
      list(APPEND cpp_sources "${src}")
    endif()
  endforeach()
  set("${out_list}" "${cpp_sources}" PARENT_SCOPE)
endfunction()
