parse:
  additional_commands:
    jegp_add_module:
      pargs:
        nargs: 1
      kwargs:
        SOURCES: +
        COMPILE_OPTIONS: +
        LINK_LIBRARIES: +
    jegp_target_link_header_units:
      pargs:
        nargs: 1+
    jegp_add_headers_test:
      pargs:
        nargs: 1+
      kwargs:
        PRIVATE_REGEXES: +
    jegp_add_test:
      pargs:
        nargs: 1+
        flags:
        - COMPILE_ONLY
      kwargs:
        SOURCES: +
        COMPILE_OPTIONS: +
        LINK_LIBRARIES: +
    jegp_add_build_error:
      pargs:
        nargs: 1+
      kwargs:
        AS: 1
        TYPE: 1
        SOURCE: 1
        COMPILE_OPTIONS: +
        LINK_LIBRARIES: +
