parse:
  additional_commands:
    _jegp_common_yaml_anchors:
      kwargs:
        PUBLIC_INTERFACE_PRIVATE: &public_interface_private
          kwargs:
            PUBLIC: +
            INTERFACE: +
            PRIVATE: +
    jegp_add_module:
      pargs: &jegp_add_module_pargs
        nargs: 1
        flags:
        - IMPORTABLE_HEADER
      kwargs:
        SOURCES: +
        COMPILE_OPTIONS: *public_interface_private
        LINK_LIBRARIES: *public_interface_private
    jegp_cpp_module:
      pargs: *jegp_add_module_pargs
    jegp_target_link_header_units:
      pargs:
        nargs: 1+
    jegp_add_headers_test:
      pargs:
        nargs: 1+
      kwargs:
        PRIVATE_REGEXES: +
    jegp_add_test:
      pargs:
        nargs: 1+
        flags:
        - COMPILE_ONLY
      kwargs:
        TYPE: 1
        SOURCES: +
        COMPILE_OPTIONS: +
        LINK_LIBRARIES: +
    jegp_add_build_error:
      pargs:
        nargs: 1+
      kwargs:
        AS: 1
        TYPE: 1
        SOURCE: 1
        COMPILE_OPTIONS: +
        LINK_LIBRARIES: +
