include: [".cmake-format-additional_commands.yaml", "modules/.detail/.cmake-format-additional_commands.yaml"]
format:
  line_width: 120
  tab_size: 2
  max_subgroups_hwrap: 4
  max_pargs_hwrap: 6
  max_rows_cmdline: 2
  separate_ctrl_name_with_space: false
  separate_fn_name_with_space: false
  dangle_parens: false
  min_prefix_chars: 8
  max_prefix_chars: 8
  max_lines_hwrap: 2
  line_ending: unix
  command_case: canonical
  keyword_case: unchanged
  always_wrap: []
  enable_sort: true
  autosort: true
  require_valid_layout: false
  layout_passes: {}
markup:
  enable_markup: false
misc:
  per_command: {}
