parse:
  additional_commands:
    jegp_add_test:
      pargs:
        nargs: 1+
        flags:
        - COMPILE_ONLY
      kwargs:
        SOURCE: 1
        SOURCES: +
        COMPILE_OPTIONS: +
        LINK_LIBRARIES: +
    jegp_add_compiler_error_test:
      pargs:
        nargs: 1+
      kwargs:
        SOURCE: 1
        COMPILE_OPTIONS: +
        LINK_LIBRARIES: +
