execute_process(
  COMMAND ${CMAKE_COMMAND} -S ${CMAKE_CURRENT_LIST_DIR} -B "${BUILD_DIR}" -D "_JEGP_TARGET=${TARGET}" -D
          "_JEGP_REQUIREMENTS_FILE=${REQUIREMENTS_FILE}" -D "_JEGP_PROJECT_BINARY_DIR=${PROJECT_BINARY_DIR}" -D
          "_JEGP_PROJECT=${PROJECT}" COMMAND_ERROR_IS_FATAL ANY)
execute_process(COMMAND ${CMAKE_COMMAND} --build "${BUILD_DIR}" COMMAND_ERROR_IS_FATAL ANY)
